// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import "LGWalletType.h"
#import <Foundation/Foundation.h>
@class LGAmount;
@class LGEventBus;
@class LGLogger;
@class LGOperationQuery;
@class LGPreferences;
@protocol LGAmountCallback;


@interface LGAccount : NSObject

- (int32_t)getIndex;

- (nullable LGOperationQuery *)queryOperations;

- (void)getBalance:(nullable id<LGAmountCallback>)callback;

- (BOOL)isSynchronizing;

- (nullable LGEventBus *)synchronize;

- (nullable LGPreferences *)getPreferences;

- (nullable LGLogger *)getLogger;

- (nullable LGPreferences *)getOperationPreferences:(nonnull NSString *)uid;

/**
 * asBitcoinLikeAccount(): Callback<BitcoinLikeAccount>;
 * asEthereumLikeAccount(): Callback<EthereumLikeAccount>;
 * asRippleLikeAccount(): Callback<RippleLikeAccount>;
 */
- (BOOL)isInstanceOfBitcoinLikeAccount;

- (BOOL)isInstanceOfEthereumLikeAccount;

- (BOOL)isInstanceOfRippleLikeAccount;

- (LGWalletType)getWalletType;

- (void)computeFees:(nullable LGAmount *)amount
           priority:(int32_t)priority
         recipients:(nonnull NSArray<NSString *> *)recipients
               data:(nonnull NSArray<NSData *> *)data
           callback:(nullable id<LGAmountCallback>)callback;

@end
