// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet_pool.djinni

#import <Foundation/Foundation.h>
@class LGBitcoinLikeWallet;


/** Interface used as a callback to iterate through mutiple BitcoinLikeWallets. */
@protocol LGBitcoinLikeWalletIterationCallback

/**
 * Called for each BitcoinLikeWallets in the set you are iterating in.
 * @param wallet The current BitcoinLikeWallet object
 * @params hasNext true if the set owns other wallet, false otherwise
 * @return true if you want to continue the iteration, false otherwise
 */
- (nullable NSNumber *)onBitcoinLikeWalletIteration:(nullable LGBitcoinLikeWallet *)wallet
                                            hasNext:(BOOL)hasNext;

@end
