// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

#import "LGBitcoinLikePickingStrategy.h"
#import "LGBitcoinLikeTransactionRequest.h"
#import <Foundation/Foundation.h>
@class LGAmount;
@class LGBitcoinLikeOutput;
@protocol LGBitcoinLikeOutputListCallback;
@protocol LGBitcoinLikePreparedTransactionCallback;
@protocol LGBitcoinLikeTransactionRequestCallback;
@protocol LGI32Callback;
@protocol LGStringCallback;


@interface LGBitcoinLikeAccount : NSObject

- (void)getUTXO:(int32_t)from
             to:(int32_t)to
       callback:(nullable id<LGBitcoinLikeOutputListCallback>)callback;

- (void)getUTXOCount:(nullable id<LGI32Callback>)callback;

- (void)pickUTXO:(nullable LGAmount *)baseFees
         outputs:(nonnull NSArray<LGBitcoinLikeOutput *> *)outputs
        strategy:(LGBitcoinLikePickingStrategy)strategy
        callback:(nullable id<LGBitcoinLikeTransactionRequestCallback>)callback;

- (void)estimateFees:(nonnull LGBitcoinLikeTransactionRequest *)request
            callback:(nullable id<LGBitcoinLikeTransactionRequestCallback>)callback;

- (void)prepareTransaction:(nonnull LGBitcoinLikeTransactionRequest *)utxo
                  callback:(nullable id<LGBitcoinLikePreparedTransactionCallback>)callback;

- (void)broadcastTransaction:(nonnull NSData *)transaction
                    callback:(nullable id<LGStringCallback>)callback;

@end
