// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

#import <Foundation/Foundation.h>

/**String keychain's name */
extern NSString * __nonnull const LGBitcoinLikeWalletConfigurationKEYCHAIN;
/**String observer's name */
extern NSString * __nonnull const LGBitcoinLikeWalletConfigurationOBSERVER;
/**String explorer's name */
extern NSString * __nonnull const LGBitcoinLikeWalletConfigurationEXPLORER;
/**String synchronizer's name */
extern NSString * __nonnull const LGBitcoinLikeWalletConfigurationSYNCHRONIZER;
/**String with Payment Script type and BIP on which hierarchical wallet is based */
extern NSString * __nonnull const LGBitcoinLikeWalletConfigurationKEYCHAINP2PKHBIP44;
/**String websocket on which observer receives notifications from explorer */
extern NSString * __nonnull const LGBitcoinLikeWalletConfigurationOBSERVERLEDGERWEBSOCKET;
/**String explorer api */
extern NSString * __nonnull const LGBitcoinLikeWalletConfigurationEXPLORERLEDGERAPI;
/**TODO */
extern NSString * __nonnull const LGBitcoinLikeWalletConfigurationSYNCHRONIZERDEFAULT;

/**Class of constants to set Bitcoin like wallet configurations */
@interface LGBitcoinLikeWalletConfiguration : NSObject

@end
