// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from emitter.djinni

#import "LGEventCode.h"
#import <Foundation/Foundation.h>
@class LGDynamicObject;
@class LGEvent;


@interface LGEvent : NSObject

- (LGEventCode)getCode;

- (nullable LGDynamicObject *)getPayload;

- (BOOL)isSticky;

- (int32_t)getStickyTag;

+ (nullable LGEvent *)newInstance:(LGEventCode)code
                          payload:(nullable LGDynamicObject *)payload;

@end
