// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http_client.djinni

#import "LGError.h"
#import <Foundation/Foundation.h>

@interface LGHttpReadBodyResult : NSObject
- (nonnull instancetype)initWithError:(nullable LGError *)error
                                 data:(nullable NSData *)data;
+ (nonnull instancetype)HttpReadBodyResultWithError:(nullable LGError *)error
                                               data:(nullable NSData *)data;

@property (nonatomic, readonly, nullable) LGError * error;

@property (nonatomic, readonly, nullable) NSData * data;

@end
