// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import "LGKeychainEngines.h"


NSString * __nonnull const LGKeychainEnginesBIP32P2PKH = @"BIP32_P2PKH";
