// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#import <Foundation/Foundation.h>

extern NSString * __nonnull const LGKeychainEnginesBIP32P2PKH;
extern NSString * __nonnull const LGKeychainEnginesBIP49P2SH;

@interface LGKeychainEngines : NSObject

@end
