// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from thread_dispatcher.djinni

#import <Foundation/Foundation.h>


@protocol LGLock

- (void)lock;

- (BOOL)tryLock;

- (void)unlock;

@end
