// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#import "LGError.h"
#import <Foundation/Foundation.h>


@protocol LGStringCallback

- (void)onCallback:(nullable NSString *)result
             error:(nullable LGError *)error;

@end
