// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#import <Foundation/Foundation.h>
@protocol LGI64TestCallback;
@protocol LGLedgerCoreTestCallback;
@protocol LGStringTestCallback;


@interface LGTestService : NSObject

- (nullable id<LGI64TestCallback>)getCallback;

- (void)setStringCallback:(nullable id<LGStringTestCallback>)callback;

- (void)setLedgerCoreCallback:(nullable id<LGLedgerCoreTestCallback>)callback;

@end
