// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet_pool.djinni

#import "LGError.h"
#import <Foundation/Foundation.h>
@class LGWalletPool;


@protocol LGWalletPoolCallback

- (void)onCallback:(nullable LGWalletPool *)result
             error:(nullable LGError *)error;

@end
