// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet_pool.djinni

#import <Foundation/Foundation.h>
@class LGWalletPoolBuilder;
@protocol LGHttpClient;
@protocol LGLogPrinter;
@protocol LGPathResolver;
@protocol LGThreadDispatcher;
@protocol LGWalletPoolBuildCallback;
@protocol LGWebSocketClient;


@interface LGWalletPoolBuilder : NSObject

- (nullable LGWalletPoolBuilder *)setHttpClient:(nullable id<LGHttpClient>)client;

- (nullable LGWalletPoolBuilder *)setWebsocketClient:(nullable id<LGWebSocketClient>)client;

- (nullable LGWalletPoolBuilder *)setPathResolver:(nullable id<LGPathResolver>)pathResolver;

- (nullable LGWalletPoolBuilder *)setLogPrinter:(nullable id<LGLogPrinter>)printer;

- (nullable LGWalletPoolBuilder *)setThreadDispatcher:(nullable id<LGThreadDispatcher>)dispatcher;

- (nullable LGWalletPoolBuilder *)setName:(nonnull NSString *)name;

- (nullable LGWalletPoolBuilder *)setPassword:(nonnull NSString *)password;

- (void)build:(nullable id<LGWalletPoolBuildCallback>)listener;

+ (nullable LGWalletPoolBuilder *)createInstance;

@end
