// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#pragma once

#include <string>

namespace ledger { namespace core { namespace api {

class BlockchainExplorerEngines {
public:
    virtual ~BlockchainExplorerEngines() {}

    static std::string const LEDGER_API;
};

} } }  // namespace ledger::core::api
