// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from validators.djinni

#ifndef DJINNI_GENERATED_COSMOSLIKEVALIDATORDISTRIBUTIONINFORMATION_HPP
#define DJINNI_GENERATED_COSMOSLIKEVALIDATORDISTRIBUTIONINFORMATION_HPP

#include <iostream>
#include <string>
#include <utility>

namespace ledger { namespace core { namespace api {

/** Distribution data for a Validator */
struct CosmosLikeValidatorDistributionInformation final {
    /** Self Bond rewards */
    std::string selfBondRewards;
    /** Accumulated validator commission */
    std::string validatorCommission;

    CosmosLikeValidatorDistributionInformation(std::string selfBondRewards_,
                                               std::string validatorCommission_)
    : selfBondRewards(std::move(selfBondRewards_))
    , validatorCommission(std::move(validatorCommission_))
    {}

    CosmosLikeValidatorDistributionInformation(const CosmosLikeValidatorDistributionInformation& cpy) {
       this->selfBondRewards = cpy.selfBondRewards;
       this->validatorCommission = cpy.validatorCommission;
    }

    CosmosLikeValidatorDistributionInformation() = default;


    CosmosLikeValidatorDistributionInformation& operator=(const CosmosLikeValidatorDistributionInformation& cpy) {
       this->selfBondRewards = cpy.selfBondRewards;
       this->validatorCommission = cpy.validatorCommission;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(selfBondRewards, validatorCommission);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(selfBondRewards, validatorCommission);
    }
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_COSMOSLIKEVALIDATORDISTRIBUTIONINFORMATION_HPP
