// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#ifndef DJINNI_GENERATED_CURRENCYLISTCALLBACK_HPP
#define DJINNI_GENERATED_CURRENCYLISTCALLBACK_HPP

#include "../utils/optional.hpp"
#include <vector>

namespace ledger { namespace core { namespace api {

struct Currency;
struct Error;

class CurrencyListCallback {
public:
    virtual ~CurrencyListCallback() {}

    virtual void onCallback(const std::experimental::optional<std::vector<Currency>> & result, const std::experimental::optional<Error> & error) = 0;
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_CURRENCYLISTCALLBACK_HPP
