// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http_client.djinni

#ifndef DJINNI_GENERATED_HTTPURLCONNECTION_HPP
#define DJINNI_GENERATED_HTTPURLCONNECTION_HPP

#include <cstdint>
#include <string>
#include <unordered_map>
#ifndef LIBCORE_EXPORT
    #if defined(_MSC_VER)
       #include <libcore_export.h>
    #else
       #define LIBCORE_EXPORT
    #endif
#endif

namespace ledger { namespace core { namespace api {

struct HttpReadBodyResult;

/**Class representing an Http connection */
class HttpUrlConnection {
public:
    virtual ~HttpUrlConnection() {}

    /**
     * Gets the HTTP response status code
     * @return The HTTP response status code
     */
    virtual int32_t getStatusCode() = 0;

    /**
     * Gets the HTTP response status text
     * @return The HTTP response status text
     */
    virtual std::string getStatusText() = 0;

    /**
     * Gets the HTTP response headers
     * @return The HTTP response headers
     */
    virtual std::unordered_map<std::string, std::string> getHeaders() = 0;

    /**
     * Reads available HTTP response body. This method will be called multiple times until it returns a empty bytes array.
     * @returns A chunk of the body data wrapped into a HttpReadBodyResult (for error management)
     */
    virtual HttpReadBodyResult readBody() = 0;
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_HTTPURLCONNECTION_HPP
