// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network.djinni

#ifndef DJINNI_GENERATED_STELLARLIKENETWORKPARAMETERS_HPP
#define DJINNI_GENERATED_STELLARLIKENETWORKPARAMETERS_HPP

#include <iostream>
#include <string>
#include <utility>

namespace ledger { namespace core { namespace api {

struct StellarLikeNetworkParameters final {
    /** Name of the network. */
    std::string Identifier;

    StellarLikeNetworkParameters(std::string Identifier_)
    : Identifier(std::move(Identifier_))
    {}

    StellarLikeNetworkParameters(const StellarLikeNetworkParameters& cpy) {
       this->Identifier = cpy.Identifier;
    }

    StellarLikeNetworkParameters() = default;


    StellarLikeNetworkParameters& operator=(const StellarLikeNetworkParameters& cpy) {
       this->Identifier = cpy.Identifier;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(Identifier);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(Identifier);
    }
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_STELLARLIKENETWORKPARAMETERS_HPP
