// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from tezos_like_wallet.djinni

#ifndef DJINNI_GENERATED_TEZOSOPERATIONTAG_HPP
#define DJINNI_GENERATED_TEZOSOPERATIONTAG_HPP

#include <functional>
#include <iostream>
#include <string>
#ifndef LIBCORE_EXPORT
    #if defined(_MSC_VER)
       #include <libcore_export.h>
    #else
       #define LIBCORE_EXPORT
    #endif
#endif

namespace ledger { namespace core { namespace api {

enum class TezosOperationTag : int {
    OPERATION_TAG_NONE,
    OPERATION_TAG_NONE1,
    OPERATION_TAG_NONE2,
    OPERATION_TAG_GENERIC,
    OPERATION_TAG_NONE4,
    OPERATION_TAG_PROPOSAL,
    OPERATION_TAG_BALLOT,
    OPERATION_TAG_REVEAL,
    OPERATION_TAG_TRANSACTION,
    OPERATION_TAG_ORIGINATION,
    OPERATION_TAG_DELEGATION,
};
LIBCORE_EXPORT  std::string to_string(const TezosOperationTag& tezosOperationTag);
LIBCORE_EXPORT  std::ostream &operator<<(std::ostream &os, const TezosOperationTag &o);

} } }  // namespace ledger::core::api

namespace std {

template <>
struct hash<::ledger::core::api::TezosOperationTag> {
    size_t operator()(::ledger::core::api::TezosOperationTag type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
#endif //DJINNI_GENERATED_TEZOSOPERATIONTAG_HPP
