// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet_pool.djinni

#ifndef DJINNI_GENERATED_WALLETPOOLBUILDCALLBACK_HPP
#define DJINNI_GENERATED_WALLETPOOLBUILDCALLBACK_HPP

#include <memory>

namespace ledger { namespace core { namespace api {

class WalletPool;
struct Error;

class WalletPoolBuildCallback {
public:
    virtual ~WalletPoolBuildCallback() {}

    virtual void onWalletPoolBuilt(const std::shared_ptr<WalletPool> & pool) = 0;

    virtual void onWalletPoolBuildError(const Error & error) = 0;
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_WALLETPOOLBUILDCALLBACK_HPP
