// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_script.djinni

#ifndef DJINNI_GENERATED_BITCOINLIKESCRIPT_HPP_JNI_
#define DJINNI_GENERATED_BITCOINLIKESCRIPT_HPP_JNI_

#include "../../include/BitcoinLikeScript.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class BitcoinLikeScript final : ::djinni::JniInterface<::ledger::core::api::BitcoinLikeScript, BitcoinLikeScript> {
public:
    using CppType = std::shared_ptr<::ledger::core::api::BitcoinLikeScript>;
    using CppOptType = std::shared_ptr<::ledger::core::api::BitcoinLikeScript>;
    using JniType = jobject;

    using Boxed = BitcoinLikeScript;

    ~BitcoinLikeScript();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<BitcoinLikeScript>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<BitcoinLikeScript>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    BitcoinLikeScript();
    friend ::djinni::JniClass<BitcoinLikeScript>;
    friend ::djinni::JniInterface<::ledger::core::api::BitcoinLikeScript, BitcoinLikeScript>;

};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_BITCOINLIKESCRIPT_HPP_JNI_
