// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

#include "Error.hpp"  // my header
#include "ErrorCode.hpp"
#include "Marshal.hpp"

namespace djinni_generated {

Error::Error() = default;

Error::~Error() = default;

auto Error::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<Error>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni_generated::ErrorCode::fromCpp(jniEnv, c.code)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.message)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto Error::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<Error>::get();
    return {::djinni_generated::ErrorCode::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_code)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_message))};
}

}  // namespace djinni_generated
