// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from emitter.djinni

#import "../../../../objc/LGEvent.h"
#import "../../../../objc/LGEventBus.h"
#import "../../../../objc/LGEventPublisher.h"
#import "../../../../objc/LGExecutionContext.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**Class representing an event publisher */
@interface RCTCoreLGEventPublisher : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGEventPublisher *objcImpl;
@end
