// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

#import "LGAmount.h"
#import "LGBitcoinLikePickingStrategy.h"
#import "LGBitcoinLikeScript.h"
#import "LGBitcoinLikeTransaction.h"
#import "LGBitcoinLikeTransactionBuilder.h"
#import "LGBitcoinLikeTransactionCallback.h"
#import "LGCurrency.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


@interface RCTCoreLGBitcoinLikeTransactionBuilder : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGBitcoinLikeTransactionBuilder *objcImpl;
@end
