// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import "../../../../objc/LGOperationListCallback.h"
#import "../../../../objc/LGOperationOrderKey.h"
#import "../../../../objc/LGOperationQuery.h"
#import "../../../../objc/LGQueryFilter.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**Class respresenting a query for a set of operations */
@interface RCTCoreLGOperationQuery : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGOperationQuery *objcImpl;
@end
