// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#import "LGError.h"
#import "LGWalletPool.h"
#import "LGWalletPoolCallbackImpl.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**
 *Callback triggered by main completed task,
 *returns optional result of template type T
 */
@interface RCTCoreLGWalletPoolCallback : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGWalletPoolCallbackImpl *objcImpl;
@end
