// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http_client.djinni

#import "../../../../objc/LGHttpRequest.h"
#import "../../../../src/objc/LGHttpClientImpl.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**Class representing the http client performing the http requests */
@interface RCTCoreLGHttpClient : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGHttpClientImpl *objcImpl;
@end
