// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from preferences.djinni

#import "LGPreferencesEditor.h"
#import "RCTCoreBaseModule.h"
#import "RCTCoreLGPreferencesEditor.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


/** Interface for editting Preferences. All changes to the editor are persisted to the disk only when comitted. */
@interface RCTCoreLGPreferencesEditor : RCTCoreBaseModule <RCTBridgeModule>
@end
