// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet_pool.djinni

#import "../../../../objc/LGBlockCallback.h"
#import "../../../../objc/LGCurrency.h"
#import "../../../../objc/LGCurrencyCallback.h"
#import "../../../../objc/LGCurrencyListCallback.h"
#import "../../../../objc/LGDatabaseBackend.h"
#import "../../../../objc/LGDynamicObject.h"
#import "../../../../objc/LGEventBus.h"
#import "../../../../objc/LGHttpClient.h"
#import "../../../../objc/LGI32Callback.h"
#import "../../../../objc/LGLogPrinter.h"
#import "../../../../objc/LGLogger.h"
#import "../../../../objc/LGPathResolver.h"
#import "../../../../objc/LGPreferences.h"
#import "../../../../objc/LGRandomNumberGenerator.h"
#import "../../../../objc/LGThreadDispatcher.h"
#import "../../../../objc/LGWalletCallback.h"
#import "../../../../objc/LGWalletListCallback.h"
#import "../../../../objc/LGWalletPool.h"
#import "../../../../objc/LGWebSocketClient.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**Class respresenting a pool of wallets */
@interface RCTCoreLGWalletPool : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGWalletPool *objcImpl;
@end
