// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_script.djinni

#import "LGBitcoinLikeScript.h"
#import "LGBitcoinLikeScriptChunk.h"
#import "RCTCoreLGBitcoinLikeScript.h"
#import "RCTCoreLGBitcoinLikeScriptChunk.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>


@interface RCTCoreLGBitcoinLikeScript : NSObject <RCTBridgeModule>
@property (nonatomic, strong) NSMutableDictionary *objcImplementations;
@end
