// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#import "RCTCoreBaseModule.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridge.h>
#import <React/RCTBridgeModule.h>

/**TODO */
@interface RCTCoreLGExtendedKeyAccountCreationInfo : RCTCoreBaseModule <RCTBridgeModule>
@end
