// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ethereum_like_wallet.djinni

#import "LGError.h"
#import "LGEthereumLikeWallet.h"
#import "LGGetEthreumLikeWalletCallbackImpl.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


@interface RCTCoreLGGetEthreumLikeWalletCallback : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGGetEthreumLikeWalletCallbackImpl *objcImpl;
@end
