// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#import "../../../../objc/LGBitcoinLikePreparedTransaction.h"
#import "../../../../objc/LGError.h"
#import "../../../../src/objc/LGBitcoinLikePreparedTransactionCallbackImpl.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**
 *Callback triggered by main completed task,
 *returns optional result of template type T
 */
@interface RCTCoreLGBitcoinLikePreparedTransactionCallback : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGBitcoinLikePreparedTransactionCallbackImpl *objcImpl;
@end
