// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#import "LGBlock.h"
#import "LGBlockCallbackImpl.h"
#import "LGError.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**
 *Callback triggered by main completed task,
 *returns optional result of template type T
 */
@interface RCTCoreLGBlockCallback : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGBlockCallbackImpl *objcImpl;
@end
