// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

#import "LGBitcoinLikeWalletConfiguration.h"
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>


/**Class of constants to set Bitcoin like wallet configurations */
@interface RCTCoreLGBitcoinLikeWalletConfiguration : NSObject <RCTBridgeModule>
@property (nonatomic, strong) LGBitcoinLikeWalletConfiguration *objcImpl;
@end
