// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

#include "BitcoinLikeAccount.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGBitcoinLikeAccount;

namespace djinni_generated {

class BitcoinLikeAccount
{
public:
    using CppType = std::shared_ptr<::ledger::core::api::BitcoinLikeAccount>;
    using CppOptType = std::shared_ptr<::ledger::core::api::BitcoinLikeAccount>;
    using ObjcType = LGBitcoinLikeAccount*;

    using Boxed = BitcoinLikeAccount;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

