// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet_pool.djinni

#import "LGBitcoinLikeNetworkParametersCallback+Private.h"
#import "LGBitcoinLikeNetworkParametersCallback.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "LGBitcoinLikeNetworkParameters+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class BitcoinLikeNetworkParametersCallback::ObjcProxy final
: public ::ledger::core::api::BitcoinLikeNetworkParametersCallback
, public ::djinni::ObjcProxyCache::Handle<ObjcType>
{
public:
    using Handle::Handle;
    void onCallback(const std::vector<::ledger::core::api::BitcoinLikeNetworkParameters> & c_params) override
    {
        @autoreleasepool {
            [Handle::get() onCallback:(::djinni::List<::djinni_generated::BitcoinLikeNetworkParameters>::fromCpp(c_params))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto BitcoinLikeNetworkParametersCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto BitcoinLikeNetworkParametersCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).Handle::get();
}

}  // namespace djinni_generated
