// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from currency.djinni

#import "LGCurrencyUnit+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto CurrencyUnit::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.name),
            ::djinni::String::toCpp(obj.symbol),
            ::djinni::String::toCpp(obj.code),
            ::djinni::I32::toCpp(obj.numberOfDecimal)};
}

auto CurrencyUnit::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[LGCurrencyUnit alloc] initWithName:(::djinni::String::fromCpp(cpp.name))
                                         symbol:(::djinni::String::fromCpp(cpp.symbol))
                                           code:(::djinni::String::fromCpp(cpp.code))
                                numberOfDecimal:(::djinni::I32::fromCpp(cpp.numberOfDecimal))];
}

}  // namespace djinni_generated
