// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#include "KeychainEngines.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGKeychainEngines;

namespace djinni_generated {

class KeychainEngines
{
public:
    using CppType = std::shared_ptr<::ledger::core::api::KeychainEngines>;
    using CppOptType = std::shared_ptr<::ledger::core::api::KeychainEngines>;
    using ObjcType = LGKeychainEngines*;

    using Boxed = KeychainEngines;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

