// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

#include "QueryFilter.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class LGQueryFilter;

namespace djinni_generated {

class QueryFilter
{
public:
    using CppType = std::shared_ptr<::ledger::core::api::QueryFilter>;
    using CppOptType = std::shared_ptr<::ledger::core::api::QueryFilter>;
    using ObjcType = LGQueryFilter*;

    using Boxed = QueryFilter;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

