// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

#pragma once

#include "../../api/BitcoinLikeConfiguration.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class BitcoinLikeConfiguration final : ::djinni::JniInterface<::ledger::core::api::BitcoinLikeConfiguration, BitcoinLikeConfiguration> {
public:
    using CppType = std::shared_ptr<::ledger::core::api::BitcoinLikeConfiguration>;
    using CppOptType = std::shared_ptr<::ledger::core::api::BitcoinLikeConfiguration>;
    using JniType = jobject;

    using Boxed = BitcoinLikeConfiguration;

    ~BitcoinLikeConfiguration();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<BitcoinLikeConfiguration>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<BitcoinLikeConfiguration>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    BitcoinLikeConfiguration();
    friend ::djinni::JniClass<BitcoinLikeConfiguration>;
    friend ::djinni::JniInterface<::ledger::core::api::BitcoinLikeConfiguration, BitcoinLikeConfiguration>;

};

}  // namespace djinni_generated
