// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_public_key_provider.djinni

#include "BitcoinPublicKeyProvider.hpp"  // my header

namespace djinni_generated {

BitcoinPublicKeyProvider::BitcoinPublicKeyProvider() : ::djinni::JniInterface<::ledger::core::api::BitcoinPublicKeyProvider, BitcoinPublicKeyProvider>() {}

BitcoinPublicKeyProvider::~BitcoinPublicKeyProvider() = default;

BitcoinPublicKeyProvider::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

BitcoinPublicKeyProvider::JavaProxy::~JavaProxy() = default;


}  // namespace djinni_generated
