// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#ifndef DJINNI_GENERATED_COSMOSLIKEMSGDEPOSIT_HPP_JNI_
#define DJINNI_GENERATED_COSMOSLIKEMSGDEPOSIT_HPP_JNI_

#include "../../api/CosmosLikeMsgDeposit.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class CosmosLikeMsgDeposit final {
public:
    using CppType = ::ledger::core::api::CosmosLikeMsgDeposit;
    using JniType = jobject;

    using Boxed = CosmosLikeMsgDeposit;

    ~CosmosLikeMsgDeposit();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    CosmosLikeMsgDeposit();
    friend ::djinni::JniClass<CosmosLikeMsgDeposit>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("co/ledger/core/CosmosLikeMsgDeposit") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/util/ArrayList;)V") };
    const jfieldID field_depositor { ::djinni::jniGetFieldID(clazz.get(), "depositor", "Ljava/lang/String;") };
    const jfieldID field_proposalId { ::djinni::jniGetFieldID(clazz.get(), "proposalId", "Ljava/lang/String;") };
    const jfieldID field_amount { ::djinni::jniGetFieldID(clazz.get(), "amount", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_COSMOSLIKEMSGDEPOSIT_HPP_JNI_
