// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#ifndef DJINNI_GENERATED_COSMOSLIKEMSGTYPE_HPP_JNI_
#define DJINNI_GENERATED_COSMOSLIKEMSGTYPE_HPP_JNI_

#include "../../api/CosmosLikeMsgType.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class CosmosLikeMsgType final : ::djinni::JniEnum {
public:
    using CppType = ::ledger::core::api::CosmosLikeMsgType;
    using JniType = jobject;

    using Boxed = CosmosLikeMsgType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<CosmosLikeMsgType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<CosmosLikeMsgType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    CosmosLikeMsgType() : JniEnum("co/ledger/core/CosmosLikeMsgType") {}
    friend ::djinni::JniClass<CosmosLikeMsgType>;
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_COSMOSLIKEMSGTYPE_HPP_JNI_
