// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#include "StellarConfiguration.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

StellarConfiguration::StellarConfiguration() : ::djinni::JniInterface<::ledger::core::api::StellarConfiguration, StellarConfiguration>("co/ledger/core/StellarConfiguration$CppProxy") {}

StellarConfiguration::~StellarConfiguration() = default;


CJNIEXPORT void JNICALL Java_co_ledger_core_StellarConfiguration_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ledger::core::api::StellarConfiguration>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
