// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from tezos_like_wallet.djinni

#include "TezosLikeOperation.hpp"  // my header
#include "TezosLikeTransaction.hpp"

namespace djinni_generated {

TezosLikeOperation::TezosLikeOperation() : ::djinni::JniInterface<::ledger::core::api::TezosLikeOperation, TezosLikeOperation>("TezosLikeOperation$CppProxy") {}

TezosLikeOperation::~TezosLikeOperation() = default;


CJNIEXPORT void JNICALL Java_TezosLikeOperation_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ledger::core::api::TezosLikeOperation>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_TezosLikeOperation_00024CppProxy_native_1getTransaction(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::ledger::core::api::TezosLikeOperation>(nativeRef);
        auto r = ref->getTransaction();
        return ::djinni::release(::djinni_generated::TezosLikeTransaction::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
