// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

#ifndef DJINNI_GENERATED_POOLCONFIGURATION_HPP
#define DJINNI_GENERATED_POOLCONFIGURATION_HPP

#include <string>

namespace ledger { namespace core { namespace api {

/**TODO */
class PoolConfiguration {
public:
    virtual ~PoolConfiguration() {}

    static std::string const DATABASE_NAME;
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_POOLCONFIGURATION_HPP
