// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#ifndef DJINNI_GENERATED_BITCOINLIKEPREPAREDTRANSACTIONCALLBACK_HPP_JNI_
#define DJINNI_GENERATED_BITCOINLIKEPREPAREDTRANSACTIONCALLBACK_HPP_JNI_

#include "../../api/BitcoinLikePreparedTransactionCallback.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class BitcoinLikePreparedTransactionCallback final : ::djinni::JniInterface<::ledger::core::api::BitcoinLikePreparedTransactionCallback, BitcoinLikePreparedTransactionCallback> {
public:
    using CppType = std::shared_ptr<::ledger::core::api::BitcoinLikePreparedTransactionCallback>;
    using CppOptType = std::shared_ptr<::ledger::core::api::BitcoinLikePreparedTransactionCallback>;
    using JniType = jobject;

    using Boxed = BitcoinLikePreparedTransactionCallback;

    ~BitcoinLikePreparedTransactionCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<BitcoinLikePreparedTransactionCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<BitcoinLikePreparedTransactionCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    BitcoinLikePreparedTransactionCallback();
    friend ::djinni::JniClass<BitcoinLikePreparedTransactionCallback>;
    friend ::djinni::JniInterface<::ledger::core::api::BitcoinLikePreparedTransactionCallback, BitcoinLikePreparedTransactionCallback>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::ledger::core::api::BitcoinLikePreparedTransactionCallback
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onCallback(const std::experimental::optional<::ledger::core::api::BitcoinLikePreparedTransaction> & result, const std::experimental::optional<::ledger::core::api::Error> & error) override;

    private:
        friend ::djinni::JniInterface<::ledger::core::api::BitcoinLikePreparedTransactionCallback, ::djinni_generated::BitcoinLikePreparedTransactionCallback>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("co/ledger/core/BitcoinLikePreparedTransactionCallback") };
    const jmethodID method_onCallback { ::djinni::jniGetMethodID(clazz.get(), "onCallback", "(Lco/ledger/core/BitcoinLikePreparedTransaction;Lco/ledger/core/Error;)V") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_BITCOINLIKEPREPAREDTRANSACTIONCALLBACK_HPP_JNI_
