// This file was GENERATED by command:
//     generate_bitcoin_fixtures.py
// DO NOT EDIT BY HAND!!!
#include "bch_xpub_fixtures.h"

namespace ledger {
	namespace testing {
		namespace bch_xpub {
			core::api::ExtendedKeyAccountCreationInfo XPUB_INFO(
			        0, {"btc"}, {"49'/1'/0'"}, {"xpub6CgNcdBp1fveikjSXRRPyY27Ma4PGM5t2GXAwAcxGtk94VpMbGmVFYPrRMqn91iXcv283wtyTPskufbRrCpppmHzfgEcc9xb8Zm4NEibzXA"}
			);
			std::shared_ptr<core::BitcoinLikeAccount> inflate(const std::shared_ptr<core::WalletPool>& pool, const std::shared_ptr<core::AbstractWallet>& wallet) {
				auto account = std::dynamic_pointer_cast<core::BitcoinLikeAccount>(wait(wallet->newAccountWithExtendedKeyInfo(XPUB_INFO)));
				soci::session sql(pool->getDatabaseSessionPool()->getPool());
				sql.begin();				account->putTransaction(sql, *core::JSONUtils::parse<core::TransactionParser>(TX_1));
				account->putTransaction(sql, *core::JSONUtils::parse<core::TransactionParser>(TX_2));
				sql.commit();
				return account;
			}
			const std::string TX_1 = "{\"inputs\": [{\"value\": 100000, \"output_index\": 0, \"output_hash\": \"7dcea6d3ebe900129fc59737c226398d3d292335f1116fbf872e081808bf7d26\", \"input_index\": 0, \"address\": \"1MAFxPyajFm2BQ3DsrRv6PwSnKi4QSEfGQ\", \"script_signature\": \"473044022053b37a3539e5b29007423e9337df7a60ec8851f69d8316f829bbc73bb5be4d0a02201fd211c8352d4482075a8c36845368a23f2727a30af94bc3da3a1a32c840e4ee012102c13586530cf1faa464688f4a0ed7bc42eb501ad7487535bd657ef771c2896237\"}], \"lock_time\": 0, \"hash\": \"c53b15d335ed931133d2b0188cc6be5b4265f5b3cbeb4e30081c3ed2d26d2c9e\", \"outputs\": [{\"script_hex\": \"76a914ffc0b7e5b6b5ac3840e5004bccc2080e08da2cf188ac\", \"output_index\": 0, \"value\": 75030, \"address\": \"1QKJBDu7JG7q2mz3v5V3Pm8vJKpKgGWLHd\"}], \"amount\": 75030, \"confirmations\": 44681, \"fees\": 24970, \"received_at\": \"2017-08-03T13:17:01Z\", \"block\": {\"time\": \"2017-08-03T13:27:47Z\", \"hash\": \"0000000000000000005390f1533cc41f7970462022707d623f567807e4439432\", \"height\": 478857}}";
			const std::string TX_2 = "{\"inputs\": [{\"value\": 1000000, \"output_index\": 0, \"output_hash\": \"89344e85521c8e70a00e0d4305f4a598a0905d537962acb78c90cef1c6b9dbbf\", \"input_index\": 0, \"address\": \"14uykiECJPWt6JAgm6SPBR2YvNR6FiKumw\", \"script_signature\": \"483045022100e004de9b4bf8d45434845e6ffd013c72c4f7606384fecc7a4452f8c66dc6026202204e91d90be5549e91ee15464f5eccb8f3b87a191a754fc7f4ab6a0e12d0cb125b01210201736137507cebd1d9c1d4646d206122e16f5388d81fe75c3acc82f5b576bac7\"}], \"lock_time\": 0, \"hash\": \"7dcea6d3ebe900129fc59737c226398d3d292335f1116fbf872e081808bf7d26\", \"outputs\": [{\"script_hex\": \"76a914dd22be4401bfe5ef1edbbab3db29dc7109f438ab88ac\", \"output_index\": 0, \"value\": 100000, \"address\": \"1MAFxPyajFm2BQ3DsrRv6PwSnKi4QSEfGQ\"}, {\"script_hex\": \"76a91412910cd79e8777085f61bb56ae6e71db0375b04388ac\", \"output_index\": 1, \"value\": 875030, \"address\": \"12hAviUbvn37t7USckRAUKnRZcR1bnMZCh\"}], \"amount\": 975030, \"confirmations\": 44687, \"fees\": 24970, \"received_at\": \"2017-08-03T12:04:29Z\", \"block\": {\"time\": \"2017-08-03T12:11:45Z\", \"hash\": \"0000000000000000007ce57198974bdceafbbad27a517733a407415636c6c644\", \"height\": 478851}}";
		}
	}
}
