// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from currency.djinni

package co.ledger.core;

/**Enum listing supported cryptocurrencies' families */
public enum WalletType {
    BITCOIN,
    ETHEREUM,
    RIPPLE,
    MONERO,
    ;
}
