
# Execution context

Runnable = interface +c {
    run();
}

ExecutionContext = interface +j +o {
 execute(runnable: Runnable);
}

LedgerCore = interface +c {
    static getStringVersion(): string;
}