// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.idl

#pragma once

#include "HttpResponseCallback.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class HttpResponseCallback final : ::djinni::JniInterface<::HttpResponseCallback, HttpResponseCallback> {
public:
    using CppType = std::shared_ptr<::HttpResponseCallback>;
    using CppOptType = std::shared_ptr<::HttpResponseCallback>;
    using JniType = jobject;

    using Boxed = HttpResponseCallback;

    ~HttpResponseCallback();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<HttpResponseCallback>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<HttpResponseCallback>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    HttpResponseCallback();
    friend ::djinni::JniClass<HttpResponseCallback>;
    friend ::djinni::JniInterface<::HttpResponseCallback, HttpResponseCallback>;

};

}  // namespace djinni_generated
