// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

package com.ledger.reactnative;

import co.ledger.core.Error;
import co.ledger.core.ErrorCode;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;

public class RCTCoreError extends ReactContextBaseJavaModule {
    private final ReactApplicationContext reactContext;
    private Map<String, Error> javaObjects;
    public Map<String, Error> getJavaObjects()
    {
        return javaObjects;
    }

    public RCTCoreError(ReactApplicationContext reactContext)
    {
        super(reactContext);
        this.reactContext = reactContext;
        this.javaObjects = new HashMap<String, Error>();
    }

    @Override
    public String getName()
    {
        return "RCTCoreError";
    }
    public void init(ErrorCode code, String message ,Promise promise) {
        Error javaResult = new Error(code, message);

        String uuid = UUID.randomUUID().toString();
        this.javaObjects.put(uuid, javaResult);
        Map<String, String> finalResult = new HashMap<String, String>();
        finalResult.put("type","RCTCoreError");
        finalResult.put("uid",uuid);
        promise.resolve(finalResult);
    }
}
