// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from addresses.djinni

package com.ledger.reactnative;

import co.ledger.core.BitcoinLikeAddress;
import co.ledger.core.BitcoinLikeExtendedPublicKey;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.WritableNativeArray;
import com.facebook.react.bridge.WritableNativeMap;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

public class RCTCoreBitcoinLikeExtendedPublicKey extends ReactContextBaseJavaModule {

    private final ReactApplicationContext reactContext;
    private Map<String, BitcoinLikeExtendedPublicKey> javaObjects;
    public Map<String, BitcoinLikeExtendedPublicKey> getJavaObjects()
    {
        return javaObjects;
    }

    public RCTCoreBitcoinLikeExtendedPublicKey(ReactApplicationContext reactContext)
    {
        super(reactContext);
        this.reactContext = reactContext;
        this.javaObjects = new HashMap<String, BitcoinLikeExtendedPublicKey>();
    }

    @Override
    public String getName()
    {
        return "RCTCoreBitcoinLikeExtendedPublicKey";
    }
    @ReactMethod
    public void release(Map<String, String> currentInstance, Promise promise)
    {
        String uid = currentInstance.get("uid");
        if (uid.length() > 0)
        {
            this.javaObjects.remove(uid);
            promise.resolve(0);
        }
        else
        {
            promise.reject("Failed to release instance of RCTCoreBitcoinLikeExtendedPublicKey", "First parameter of RCTCoreBitcoinLikeExtendedPublicKey::release should be an instance of RCTCoreBitcoinLikeExtendedPublicKey");
        }
    }
    @ReactMethod
    public void log(Promise promise)
    {
        WritableNativeArray result = new WritableNativeArray();
        for (Map.Entry<String, BitcoinLikeExtendedPublicKey> elem : this.javaObjects.entrySet())
        {
            result.pushString(elem.getKey());
        }
        promise.resolve(result);
    }
    @ReactMethod
    public void flush(Promise promise)
    {
        this.javaObjects.clear();
        promise.resolve(0);
    }

    @ReactMethod
    public void derive(Map<String, String> currentInstance, String path, Promise promise) {
        try
        {
            String sUid = currentInstance.get("uid");

            BitcoinLikeExtendedPublicKey currentInstanceObj = this.javaObjects.get(sUid);

            BitcoinLikeAddress javaResult = currentInstanceObj.derive(path);

            String uuid = UUID.randomUUID().toString();
            RCTCoreBitcoinLikeAddress rctImpl_javaResult = this.reactContext.getNativeModule(RCTCoreBitcoinLikeAddress.class);
            rctImpl_javaResult.getJavaObjects().put(uuid, javaResult);
            WritableNativeMap result = new WritableNativeMap();
            result.putString("type","RCTCoreBitcoinLikeAddress");
            result.putString("uid",uuid);

            promise.resolve(result);
        }
        catch(Exception e)
        {
            promise.reject(e.toString(), e.getMessage());
        }
    }
    @ReactMethod
    public void derivePublicKey(Map<String, String> currentInstance, String path, Promise promise) {
        try
        {
            String sUid = currentInstance.get("uid");

            BitcoinLikeExtendedPublicKey currentInstanceObj = this.javaObjects.get(sUid);

            byte[] javaResult = currentInstanceObj.derivePublicKey(path);
            WritableNativeMap result = new WritableNativeMap();
            String finalJavaResult = new String(javaResult);
            result.putString("value", finalJavaResult);

            promise.resolve(result);
        }
        catch(Exception e)
        {
            promise.reject(e.toString(), e.getMessage());
        }
    }
    @ReactMethod
    public void deriveHash160(Map<String, String> currentInstance, String path, Promise promise) {
        try
        {
            String sUid = currentInstance.get("uid");

            BitcoinLikeExtendedPublicKey currentInstanceObj = this.javaObjects.get(sUid);

            byte[] javaResult = currentInstanceObj.deriveHash160(path);
            WritableNativeMap result = new WritableNativeMap();
            String finalJavaResult = new String(javaResult);
            result.putString("value", finalJavaResult);

            promise.resolve(result);
        }
        catch(Exception e)
        {
            promise.reject(e.toString(), e.getMessage());
        }
    }
    @ReactMethod
    public void toBase58(Map<String, String> currentInstance, Promise promise) {
        try
        {
            String sUid = currentInstance.get("uid");

            BitcoinLikeExtendedPublicKey currentInstanceObj = this.javaObjects.get(sUid);

            String javaResult = currentInstanceObj.toBase58();
            WritableNativeMap result = new WritableNativeMap();
            result.putString("value", javaResult);

            promise.resolve(result);
        }
        catch(Exception e)
        {
            promise.reject(e.toString(), e.getMessage());
        }
    }
    @ReactMethod
    public void getRootPath(Map<String, String> currentInstance, Promise promise) {
        try
        {
            String sUid = currentInstance.get("uid");

            BitcoinLikeExtendedPublicKey currentInstanceObj = this.javaObjects.get(sUid);

            String javaResult = currentInstanceObj.getRootPath();
            WritableNativeMap result = new WritableNativeMap();
            result.putString("value", javaResult);

            promise.resolve(result);
        }
        catch(Exception e)
        {
            promise.reject(e.toString(), e.getMessage());
        }
    }
}
