// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from configuration.djinni

package com.ledger.reactnative;

import co.ledger.core.BlockchainExplorerEngines;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

/**TODO */
public class RCTCoreBlockchainExplorerEngines extends ReactContextBaseJavaModule {

    private final ReactApplicationContext reactContext;
    private Map<String, BlockchainExplorerEngines> javaObjects;
    public Map<String, BlockchainExplorerEngines> getJavaObjects()
    {
        return javaObjects;
    }

    public RCTCoreBlockchainExplorerEngines(ReactApplicationContext reactContext)
    {
        super(reactContext);
        this.reactContext = reactContext;
        this.javaObjects = new HashMap<String, BlockchainExplorerEngines>();
    }

    @Override
    public String getName()
    {
        return "RCTCoreBlockchainExplorerEngines";
    }

}
