// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

package com.ledger.reactnative;

import BitcoinLikeTransactionCallbackImpl;
import RCTCoreBitcoinLikeTransaction;
import RCTCoreError;
import co.ledger.core.BitcoinLikeTransaction;
import co.ledger.core.Error;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import java.util.UUID;;

/**
 *Callback triggered by main completed task,
 *returns optional result of template type T
 */
public class RCTCoreBitcoinLikeTransactionCallback extends BitcoinLikeTransactionCallback {
    public Promise promise;
    public Bridge bridge;
    public static RCTCoreBitcoinLikeTransactionCallback initWithPromise(Promise promise, (RCTBridge *) bridge)
    {
        RCTCoreBitcoinLikeTransactionCallback callback = new RCTCoreBitcoinLikeTransactionCallback();
        if(callback)
        {
            callback.promise = promise;
            callback.bridge = bridge;
        }
        return callback;
    }
    /**
     * Method triggered when main task complete
     * @params result optional of type T, non null if main task failed
     * @params error optional of type Error, non null if main task succeeded
     */
    public void onCallback(BitcoinLikeTransaction result, Error error, ) {
        try
        {
            if (error)
            {
                self.promise.reject(ERROR, error.message);
            }
            String uuid = UUID.randomUUID().toString();
            RCTCoreBitcoinLikeTransaction rctImpl_result = (RCTCoreBitcoinLikeTransaction)self.bridge moduleForName("RCTCoreBitcoinLikeTransaction");
            rctImpl_result.javaObjects.put(uuid, result);
            Map<String, String> converted_result = new HashMap<String, String>();
            converted_result.put("type","RCTCoreBitcoinLikeTransaction");
            converted_result.put("uid",uuid);

            self.promise.resolve(converted_result);
        }
        catch(Exception e)
        {
            self.promise.reject(ERROR, e);
        }
    }
}
