// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from amount.djinni

package com.ledger.reactnative;

import co.ledger.core.FormatRules;
import co.ledger.core.RoundingMode;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Optional;

/**TODO */
public class RCTCoreFormatRules extends ReactContextBaseJavaModule {
    private final ReactApplicationContext reactContext;
    private Map<String, FormatRules> javaObjects;
    public Map<String, FormatRules> getJavaObjects()
    {
        return javaObjects;
    }

    public RCTCoreFormatRules(ReactApplicationContext reactContext)
    {
        super(reactContext);
        this.reactContext = reactContext;
        this.javaObjects = new HashMap<String, FormatRules>();
    }

    @Override
    public String getName()
    {
        return "RCTCoreFormatRules";
    }
    public void init(RoundingMode roundingMode, int maxNumberOfDecimals ,Promise promise) {
        FormatRules javaResult = new FormatRules(roundingMode, maxNumberOfDecimals);

        String uuid = UUID.randomUUID().toString();
        this.javaObjects.put(uuid, javaResult);
        Map<String, String> finalResult = new HashMap<String, String>();
        finalResult.put("type","RCTCoreFormatRules");
        finalResult.put("uid",uuid);
        promise.resolve(finalResult);
    }
}
