// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

#ifndef DJINNI_GENERATED_WALLETPOOLCALLBACK_HPP
#define DJINNI_GENERATED_WALLETPOOLCALLBACK_HPP

#include "../utils/optional.hpp"
#include <memory>

namespace ledger { namespace core { namespace api {

class WalletPool;
struct Error;

class WalletPoolCallback {
public:
    virtual ~WalletPoolCallback() {}

    virtual void onCallback(const std::shared_ptr<WalletPool> & result, const std::experimental::optional<Error> & error) = 0;
};

} } }  // namespace ledger::core::api
#endif //DJINNI_GENERATED_WALLETPOOLCALLBACK_HPP
