#!/bin/sh

# project new <coin-id> [--force]
usage() {
  echo $1
  exit $2
}

cmd_project_new() {
  if [[ -z "$1" ]];
  then
    usage "please provide the name of the currency" 1
  fi

  coin_name="$1"
  project_name="ledger-core-$coin_name"
  echo "—> project $project_name"

  if [[ -d "./$project_name" ]];
  then
    if [[ ! "$2" == "--force" ]];
    then
      usage "project already created; aborting…" 1
    fi
  fi

  echo "—> creating files hierarchy"
  mkdir -p $project_name/{build,idl,inc/$coin_name/database,src/$coin_name/database}
  touch $project_name/README.md

  echo "—> symlinking ledger-core’s libraries"
  ln -sf $PWD/ledger-core/lib $project_name/lib
  ln -sf $PWD/ledger-core/cmake $project_name/cmake

  echo "—> generating CMake configuration"
  sed -e s/\$project_name/$project_name/g ./tools/templates/CMakeLists-project.txt.tpl > $project_name/CMakeLists.txt
  sed -e s/\$project_name/$project_name/g -e s/\$coin_name/$coin_name/g ./tools/templates/CMakeLists-project-src.txt.tpl > $project_name/src/CMakeLists.txt

  echo "—> generating IDL entry point"
  cp ./tools/templates/idl.djinni $project_name/idl/

  echo "—> creating migrations files"
  sed s/\$project_name/$coin_name/g ./tools/templates/Migrations.hpp > $project_name/inc/$coin_name/database/Migrations.hpp
  sed s/\$project_name/$coin_name/g ./tools/templates/Migrations.cpp > $project_name/src/$coin_name/database/Migrations.cpp
}

cmd_project_idl() {
  if [[ -z "$1" ]];
  then
    usage "please provide the name of the currency" 1
  fi

  ./tools/idl_interfaces.sh ledger-core $1
}

cmd_project() {
  case "$1" in
    "new")
      shift
      cmd_project_new $*
      ;;

    "api")
      shift
      cmd_project_idl $*
      ;;

    *)
      usage "project usage" 1
      ;;
  esac
}

cmd_idl() {
  if [[ ! -z "$*" ]];
  then
    usage "too many arguments; generating the API for Ledger Core doesn’t require any argument" 1
  fi

  ./tools/idl_interfaces.sh ledger-core
}

case "$1" in
  "project")
    shift
    cmd_project $*
    ;;

  "api")
    shift
    cmd_idl $*
    ;;

  *)
    usage "usage" 2
    ;;
esac
