function(set_clang_format files)
  find_program(CLANG_FORMAT "clang-format")
  if(CLANG_FORMAT)
    message(STATUS "Using clang-format")
    add_custom_target(clang-format COMMAND ${CLANG_FORMAT} --verbose -i -style=file ${files})
  else()
    message(STATUS "clang-format not found")
  endif()
endfunction()

function(set_cmake_format configuration_path files)
  find_program(CMAKE_FORMAT "cmake-format")
  if(CMAKE_FORMAT)
    message(STATUS "Using cmake-format")
    add_custom_target(cmake-format COMMAND ${CMAKE_FORMAT} ${files} -c ${configuration_path} -i -l info)
  else()
    message(STATUS "cmake-format not found")
  endif()
endfunction()