option (CCACHE "Use ccache compilation optimization" OFF)

find_program(CCACHE_FOUND ccache)
if(CCACHE_FOUND)
    message(STATUS "ccache found: ${CCACHE_FOUND}")
    if(CCACHE)
        set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
        set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
    else(CCACHE)
        message(STATUS "ccache NOT ENABLED via 'CCACHE' variable!")
    endif(CCACHE)
else(CCACHE_FOUND)
    message(STATUS "ccache not found")
endif(CCACHE_FOUND)