// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_like_wallet.djinni

package co.ledger.core;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class BitcoinLikeInput {
    public abstract String getAddress();

    public abstract String getAddressDerivationPath();

    public abstract Amount getValue();

    public abstract boolean isCoinbase();

    public abstract String getCoinbase();

    public abstract String getPreviousTxHash();

    public abstract int getPreviousOutputIndex();

    private static final class CppProxy extends BitcoinLikeInput
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String getAddress()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getAddress(this.nativeRef);
        }
        private native String native_getAddress(long _nativeRef);

        @Override
        public String getAddressDerivationPath()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getAddressDerivationPath(this.nativeRef);
        }
        private native String native_getAddressDerivationPath(long _nativeRef);

        @Override
        public Amount getValue()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getValue(this.nativeRef);
        }
        private native Amount native_getValue(long _nativeRef);

        @Override
        public boolean isCoinbase()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isCoinbase(this.nativeRef);
        }
        private native boolean native_isCoinbase(long _nativeRef);

        @Override
        public String getCoinbase()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getCoinbase(this.nativeRef);
        }
        private native String native_getCoinbase(long _nativeRef);

        @Override
        public String getPreviousTxHash()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getPreviousTxHash(this.nativeRef);
        }
        private native String native_getPreviousTxHash(long _nativeRef);

        @Override
        public int getPreviousOutputIndex()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getPreviousOutputIndex(this.nativeRef);
        }
        private native int native_getPreviousOutputIndex(long _nativeRef);
    }
}
