// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from bitcoin_public_key_provider.djinni

package co.ledger.core;

public abstract class BitcoinLikeBase58ExtendedPublicKeyProvider {
    public abstract void get(String deviceId, String path, BitcoinLikeNetworkParameters params, StringCompletionBlock completion);
}
