// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from currency.djinni

package co.ledger.core;

import java.util.ArrayList;

public final class Currency {


    /*package*/ final WalletType walletType;

    /*package*/ final String name;

    /*package*/ final int bip44CoinType;

    /*package*/ final String paymentUriScheme;

    /*package*/ final ArrayList<CurrencyUnit> units;

    /*package*/ final BitcoinLikeNetworkParameters bitcoinLikeNetworkParameters;

    public Currency(
            WalletType walletType,
            String name,
            int bip44CoinType,
            String paymentUriScheme,
            ArrayList<CurrencyUnit> units,
            BitcoinLikeNetworkParameters bitcoinLikeNetworkParameters) {
        this.walletType = walletType;
        this.name = name;
        this.bip44CoinType = bip44CoinType;
        this.paymentUriScheme = paymentUriScheme;
        this.units = units;
        this.bitcoinLikeNetworkParameters = bitcoinLikeNetworkParameters;
    }

    public WalletType getWalletType() {
        return walletType;
    }

    public String getName() {
        return name;
    }

    public int getBip44CoinType() {
        return bip44CoinType;
    }

    public String getPaymentUriScheme() {
        return paymentUriScheme;
    }

    public ArrayList<CurrencyUnit> getUnits() {
        return units;
    }

    public BitcoinLikeNetworkParameters getBitcoinLikeNetworkParameters() {
        return bitcoinLikeNetworkParameters;
    }

    @Override
    public String toString() {
        return "Currency{" +
                "walletType=" + walletType +
                "," + "name=" + name +
                "," + "bip44CoinType=" + bip44CoinType +
                "," + "paymentUriScheme=" + paymentUriScheme +
                "," + "units=" + units +
                "," + "bitcoinLikeNetworkParameters=" + bitcoinLikeNetworkParameters +
        "}";
    }

}
