// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.idl

package co.ledger.core;

public abstract class ExecutionContext {
    public abstract void execute(Runnable runnable);
}
