// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from callback.djinni

package co.ledger.core;

public abstract class I64Callback {
    public abstract void onCallback(Long result, Error error);
}
