// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wallet.djinni

package co.ledger.core;

public enum WalletType {
    BITCOIN,
    ETHEREUM,
    RIPPLE,
    MONERO,
    ;
}
